{"name": "test_create_user_duplicate_email", "status": "broken", "statusDetails": {"message": "NameError: name 'requests' is not defined", "trace": "base_url = 'https://gorest.co.in', headers = {'Authorization': 'Bearer 8a410a5aba44bcc3c44e06a4894f4ac5b024815a58b0af400f74afc7e762cef0'}\nend_point = '/public/v2/users/'\n\n    @allure.feature(\"User Management\")\n    @allure.story(\"Negative Scenarios\")\n    @pytest.mark.negative\n    def test_create_user_duplicate_email(base_url, headers, end_point):\n        \"\"\"Verify creating a user with duplicate email fails (422)\"\"\"\n        email = \"duplicate@user.com\"\n        data = {\"name\": \"first_user\", \"email\": email, \"gender\": \"male\", \"status\": \"active\"}\n    \n        # Create first user\n>       requests.post(base_url + end_point, headers=headers, json=data, timeout=10)\n        ^^^^^^^^\nE       NameError: name 'requests' is not defined\n\ntests/test_users_negative.py:66: NameError"}, "description": "Verify creating a user with duplicate email fails (422)", "start": 1757600249586, "stop": 1757600249586, "uuid": "029203ee-9da3-484f-8866-cd944ae4b996", "historyId": "4882ef3bb591f60ce45ceee863ac9d7e", "testCaseId": "4882ef3bb591f60ce45ceee863ac9d7e", "fullName": "tests.test_users_negative#test_create_user_duplicate_email", "labels": [{"name": "story", "value": "Negative Scenarios"}, {"name": "feature", "value": "User Management"}, {"name": "tag", "value": "negative"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_users_negative"}, {"name": "host", "value": "riju-Inspiron-15-3515"}, {"name": "thread", "value": "733435-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_users_negative"}], "titlePath": ["tests", "test_users_negative.py"]}